### ISSUE TITLE
Allow tutors to check attendance

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/ArtemisExamChecker#16]
I want to suggest a feature/improvement.

Problem:
Usually, tutors check attendance during an exam. This requires us to give tutors temporarily the instructor role. Hence, they can access the course, exam, and exercise configurations.

Solution:
Give tutors access to the feature during the examination period.

**Comment by nityanandaz** [comment]
| Student | Tutor | Instructor |
|--------|--------|--------|
| ![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-11-09 at 16 16 11](https://github.com/ls1intum/ArtemisExamChecker/assets/23535000/9a05f004-3576-4765-8905-3295d6b0e83a) | ![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-11-09 at 16 16 11](https://github.com/ls1intum/ArtemisExamChecker/assets/23535000/9a05f004-3576-4765-8905-3295d6b0e83a) | ![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-11-09 at 16 15 47](https://github.com/ls1intum/ArtemisExamChecker/assets/23535000/44a8a41b-29a8-4c5f-9341-f106cd906930) |
